server:
  port: 8080

spring:
  application:
    name: lab-gateway
  config:
    import:
      - optional:nacos:common-dev.yml
      - optional:nacos:sentinel-dev.yml
      - optional:nacos:redis-dev.yml
      - optional:nacos:sa-token.yml
      - optional:nacos:management.yml
      - optional:nacos:lab-gateway-dev.yml
  cloud:
    nacos:
      server-addr: 192.168.179.128:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
      config:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
        file-extension: yml
    sentinel:
      datasource:
        gw-flow-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            namespace: ${spring.cloud.nacos.config.namespace}
            data-id: ${spring.application.name}-gw-flow-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
        gw-api-group-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            namespace: ${spring.cloud.nacos.config.namespace}
            data-id: ${spring.application.name}-gw-api-group-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw-api-group
