server:
  port: 8901
spring:
  application:
    name: resource-server
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1   # 与 auth-server 使用同一 Redis 库，共享 Token

sa-token:
  token-name: Authorization
  is-log: true
