spring:
  application:
    name: governance-lab
  config:
    import:
      - nacos:common-dev.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:management.yml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: 192.168.179.128:8848
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      discovery:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
        metadata:
          version: 0.1.0
          capability: governance
      config:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
