target: all

multitenancy_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9009

blocks_storage:
  backend: filesystem

  filesystem:
    dir: /data/blocks

compactor:
  data_dir: /data/compactor

ruler_storage:
  backend: filesystem

  filesystem:
    dir: /data/ruler

alertmanager_storage:
  backend: filesystem

  filesystem:
    dir: /data/alertmanager

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory

    replication_factor: 1

store_gateway:
  sharding_ring:
    kvstore:
      store: inmemory

    replication_factor: 1

ruler:
  enable_api: true

  ring:
    kvstore:
      store: inmemory
