server:
  port: 8081

spring:
  application:
    name: lab-config-center
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:common-dev.yml
      # 格式：nacos:{dataId}?group={group}&refreshEnabled=true
      # 1. 微服务自身配置（DataId 规范：{appName}-{profile}.{ext}）
#      - nacos:common-dev.yml
      # 2. 多环境配置（通过 profile 区分）
#      - optional:nacos:lab-config-center-${spring.profiles.active}.yaml
      # 3. 共享配置（多个服务公用，如数据源、Redis 等）
#      - optional:nacos:common-datasource.yaml?group=SHARED_GROUP&refreshEnabled=true
#      - optional:nacos:common-redis.yaml?group=SHARED_GROUP&refreshEnabled=true
      # 4. 扩展配置（优先级高于 shared-configs）
#      - optional:nacos:lab-config-center-ext.yaml?refreshEnabled=true

  cloud:
    nacos:
      # Nacos Server 地址（统一在此配置，discovery 和 config 共用）
      server-addr: 192.168.179.128:8848
      username: nacos
      password: nacos
      config:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
        file-extension: yml

# Actuator 暴露 refresh 端点（手动触发配置刷新）
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
  endpoint:
    health:
      show-details: always

# 本地演示配置（会被 Nacos 中的配置覆盖）
app:
  name: lab-config-center
  version: 1.0.0
  description: 这是本地默认配置，会被 Nacos 动态配置覆盖
