services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: lab-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - middleware-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: lab-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      TZ: Asia/Shanghai
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - middleware-net

volumes:
  prometheus-data:
  grafana-data:

networks:
  middleware-net:
    external: true
