server:
  port: 8092

spring:
  application:
    name: registry-consumer
  cloud:
    nacos:
      server-addr: 192.168.179.128:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 85baacbf-ae17-4c72-9a35-348679962b0e
        group: DEFAULT_GROUP
