server:
  port: 8092

spring:
  application:
    name: registry-consumer
  cloud:
    nacos:
      server-addr: ${LAB_NACOS_ADDR:127.0.0.1:8848}
      username: ${LAB_NACOS_USERNAME:nacos}
      password: ${LAB_NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${LAB_NACOS_NAMESPACE:}
        group: ${LAB_NACOS_GROUP:DEFAULT_GROUP}
