server:
  port: 8600
spring:
  application:
    name: lab-multi-datasource
  # MySQL 数据源（MyBatis-Flex 使用）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/multi_ds?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  # MongoDB 数据源（Spring Data MongoDB 使用）
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/multi_ds
      # 如有认证：mongodb://user:password@127.0.0.1:27017/multi_ds
