lab:
  message:
    rocketmq:
      adapter:
        enabled: true
        consumers:
          lab_order_created_events:
            message-lab-order-primary:
              consume-mode: CONCURRENTLY
              consume-thread-number: 2
            message-lab-order-audit:
              consume-mode: CONCURRENTLY
              consume-thread-number: 2

# Official Apache RocketMQ Spring (sole native config source)
rocketmq:
  name-server: 192.168.179.128:9876
  producer:
    group: ${spring.application.name}-producer
